CREATE DATABASE PROYEK_PBD
ON PRIMARY (
	NAME = Proyek_Pbd,
	FILENAME = 'G:\Nanda_2\0-Kuliah\Semester-IV\Perancangan-BD\Proyek_Pbd\PROYEK_PBD.mdf',
	SIZE = 10,
	MAXSIZE = 50,
	FILEGROWTH = 2)
LOG ON (
	NAME = db_psb_log,
	FILENAME = 'G:\Nanda_2\0-Kuliah\Semester-IV\Perancangan-BD\Proyek_Pbd\PROYEK_PBDlog.ldf',
	SIZE = 3,
	MAXSIZE = 20,
	FILEGROWTH = 1)

	USE PROYEK_PBD

	--MEMBUAT TABLE
	CREATE TABLE SISWA (
	ID_SISWA CHAR (12) NOT NULL PRIMARY KEY,
	NAMA_SISWA VARCHAR(100) NOT NULL,
	ALAMAT_SISWA VARCHAR (100) NOT NULL,
	NO_TELP_SISWA INT NOT NULL,
	EMAIL_SISWA VARCHAR (50) NOT NULL,
	TH_ANGKATAN INT NOT NULL,
	JURUSAN VARCHAR (25) NOT NULL,
	ID_STAFF CHAR(12) NOT NULL FOREIGN KEY REFERENCES STAFF(ID_STAFF),
	NILAI_UJIAN INT NOT NULL,
	STATUS_SISWA CHAR (10) NOT NULL
	)

	CREATE TABLE JURUSAN(
	ID_JURUSAN CHAR(8) NOT NULL PRIMARY KEY,
	NAMA_JURUSAN VARCHAR(25) NOT NULL
	)

	CREATE TABLE STAFF(
	ID_STAFF CHAR (12) NOT NULL PRIMARY KEY,
	PASS_STAFF VARCHAR (25) NOT NULL,
	NAMA_STAFF VARCHAR (100) NOT NULL,
	ALAMAT_STAFF VARCHAR (100) NOT NULL,
	NO_TELP_STAFF INT NOT NULL,
	EMAIL_STAFF VARCHAR (50) NOT NULL
	)

	CREATE TABLE GURU(
	ID_GURU CHAR (12) NOT NULL PRIMARY KEY,
	NAMA_GURU VARCHAR (100) NOT NULL,
	ALAMAT_GURU VARCHAR (100) NOT NULL,
	NO_TELP_GURU INT NOT NULL,
	EMAIL_STAFF VARCHAR (50) NOT NULL,
	JABATAN CHAR (25) NOT NULL
	)

	CREATE TABLE PEMBAYARAN (
	ID_PEMBAYARAN CHAR (12) NOT NULL PRIMARY KEY,
	NAMA_PEMBAYARAN VARCHAR (100) NOT NULL,
	TOTAL FLOAT NOT NULL
	)

	CREATE TABLE DETAIL_TRANSAKSI (
	ID_NOTA CHAR (12) NOT NULL PRIMARY KEY,
	ID_PEMBAYARAN CHAR (12) NOT NULL FOREIGN KEY REFERENCES PEMBAYARAN(ID_PEMBAYARAN),
	TOTAL_BARANG INT NOT NULL
	)

	CREATE TABLE KELAS (
	ID_KELAS CHAR (12) NOT NULL PRIMARY KEY,
	ID_SISWA CHAR (12) NOT NULL FOREIGN KEY REFERENCES SISWA(ID_SISWA),
	ID_GURU CHAR (12) NOT NULL FOREIGN KEY REFERENCES GURU(ID_GURU)
	) 
