CREATE DATABASE PROYEK_PBD
ON PRIMARY (
	NAME = Proyek_Pbd,
	FILENAME = 'G:\Nanda_2\0-Kuliah\Semester-IV\Perancangan-BD\Proyek_Pbd\PROYEK_PBD.mdf',
	SIZE = 10,
	MAXSIZE = 50,
	FILEGROWTH = 2)
LOG ON (
	NAME = db_psb_log,
	FILENAME = 'G:\Nanda_2\0-Kuliah\Semester-IV\Perancangan-BD\Proyek_Pbd\PROYEK_PBDlog.ldf',
	SIZE = 3,
	MAXSIZE = 20,
	FILEGROWTH = 1)

	USE PROYEK_PBD

	--MEMBUAT TABLE
	CREATE TABLE SISWA (
	NISN CHAR (12) NOT NULL PRIMARY KEY,
	NAMA_SISWA VARCHAR(100) NOT NULL,
	ALAMAT_SISWA VARCHAR (100) NOT NULL,
	EMAIL_SISWA VARCHAR (50) NOT NULL
	)

	CREATE TABLE STAFF(
	NIK CHAR (12) NOT NULL PRIMARY KEY,
	PASS_STAFF VARCHAR (25) NOT NULL,
	USERNAME VARCHAR (29) NOT NULL,
	NAMA_STAFF VARCHAR (100) NOT NULL,
	ALAMAT_STAFF VARCHAR (100) NOT NULL,
	NO_TELP_STAFF INT NOT NULL
	)
